### ISSUE TITLE
Pyromid v2 

### ISSUE THREAD

**Issue by Tohelo101** [Pymmdrza/Pyromid#15]
Hello im trying to run Pyromid V2 but i get this 
       ██████╗ ██╗   ██╗██████╗  ██████╗ ███╗   ███╗██╗██████╗ 
        ██╔══██╗╚██╗ ██╔╝██╔══██╗██╔═══██╗████╗ ████║██║██╔══██╗
        ██████╔╝ ╚████╔╝ ██████╔╝██║   ██║██╔████╔██║██║██║  ██║
        ██╔═══╝   ╚██╔╝  ██╔══██╗██║   ██║██║╚██╔╝██║██║██║  ██║
        ██║        ██║   ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║██████╔╝
        ╚═╝        ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝╚═════╝ 
╔═╗╦═╗╔═╗╔═╗╦═╗╔═╗╔╦╗╔╦╗╔═╗╦═╗  ╔╦╗╔╦╗╔╦╗╦═╗╔═╗╔═╗ ╔═╗╔═╗╔╦╗
╠═╝╠╦╝║ ║║ ╦╠╦╝╠═╣║║║║║║║╣ ╠╦╝  ║║║║║║ ║║╠╦╝╔═╝╠═╣ ║  ║ ║║║║
╩  ╩╚═╚═╝╚═╝╩╚═╩ ╩╩ ╩╩ ╩╚═╝╩╚═  ╩ ╩╩ ╩═╩╝╩╚═╚═╝╩ ╩o╚═╝╚═╝╩ ╩
➜ Pyromid v2 Ⓟ Powered By CryptoFuzz - Exclusive MMDRZA.COM
▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
[►] Import Rich File : Rich.txt                
[►] Method Generated : Random Without Repeat.    
[►] Address Type     : Compressed / Uncompressed.
[►] Max Decimal (HEX): 115792089237316195423570985008687907852837564279074904382605163141518161494336         
[►] Result Checked   : 0                   
[►] Matched Address  : 0                   

Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pc1/Pyromid/Pyromid_V2.py", line 103, in <module>
    MainCheck()
  File "/home/pc1/Pyromid/Pyromid_V2.py", line 78, in MainCheck
    CompressAddr = Hex_To_Addr(privatekey, True)
  File "/home/pc1/Pyromid/Pyromid_V2.py", line 35, in Hex_To_Addr
    return co.hex_to_addr(hexed, compress)
  File "/home/pc1/.local/lib/python3.10/site-packages/cryptofuzz/utils.py", line 149, in hex_to_addr
    return self.bytes_to_addr(seed, True)
  File "/home/pc1/.local/lib/python3.10/site-packages/cryptofuzz/utils.py", line 230, in bytes_to_addr
    return self.pub_to_addr(public_key=pub)
  File "/home/pc1/.local/lib/python3.10/site-packages/cryptofuzz/utils.py", line 282, in pub_to_addr
    ripemd160 = hashlib.new('ripemd160')
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type ripemd160

**Comment by Pymmdrza** [comment]
@Tohelo101 
![REC_02-04-2024 13-59-12](https://github.com/Pymmdrza/Pyromid/assets/95309780/f3796930-4e4c-4110-9973-eb444b3ce00a)
